# Generated by Django 2.1.1 on 2018-10-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20181005_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='lon',
        ),
    ]
