# Generated by Django 2.1.1 on 2018-10-05 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import indonesia.interfaces


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabupatenBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('gid_1', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('nl_name_1', models.CharField(max_length=80)),
                ('gid_2', models.CharField(max_length=80)),
                ('name_2', models.CharField(max_length=80)),
                ('varname_2', models.CharField(max_length=80)),
                ('nl_name_2', models.CharField(max_length=80)),
                ('type_2', models.CharField(max_length=80)),
                ('engtype_2', models.CharField(max_length=80)),
                ('cc_2', models.CharField(max_length=80)),
                ('hasc_2', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            bases=(models.Model, indonesia.interfaces.IndonesiaAdministrativeArea, indonesia.interfaces.AreaPropertyInfo),
        ),
        migrations.CreateModel(
            name='KecamatanBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('gid_1', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('nl_name_1', models.CharField(max_length=80)),
                ('gid_2', models.CharField(max_length=80)),
                ('name_2', models.CharField(max_length=80)),
                ('nl_name_2', models.CharField(max_length=80)),
                ('gid_3', models.CharField(max_length=80)),
                ('name_3', models.CharField(max_length=80)),
                ('varname_3', models.CharField(max_length=80)),
                ('nl_name_3', models.CharField(max_length=80)),
                ('type_3', models.CharField(max_length=80)),
                ('engtype_3', models.CharField(max_length=80)),
                ('cc_3', models.CharField(max_length=80)),
                ('hasc_3', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            bases=(models.Model, indonesia.interfaces.IndonesiaAdministrativeArea, indonesia.interfaces.AreaPropertyInfo),
        ),
        migrations.CreateModel(
            name='KelurahanBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('gid_1', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('gid_2', models.CharField(max_length=80)),
                ('name_2', models.CharField(max_length=80)),
                ('gid_3', models.CharField(max_length=80)),
                ('name_3', models.CharField(max_length=80)),
                ('gid_4', models.CharField(max_length=80)),
                ('name_4', models.CharField(max_length=80)),
                ('varname_4', models.CharField(max_length=80)),
                ('type_4', models.CharField(max_length=80)),
                ('engtype_4', models.CharField(max_length=80)),
                ('cc_4', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            bases=(models.Model, indonesia.interfaces.IndonesiaAdministrativeArea, indonesia.interfaces.AreaPropertyInfo),
        ),
        migrations.CreateModel(
            name='KelurahanBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Buildings')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indonesia.KelurahanBorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinsiBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=80)),
                ('name_0', models.CharField(max_length=80)),
                ('gid_1', models.CharField(max_length=80)),
                ('name_1', models.CharField(max_length=80)),
                ('varname_1', models.CharField(max_length=80)),
                ('nl_name_1', models.CharField(max_length=80)),
                ('type_1', models.CharField(max_length=80)),
                ('engtype_1', models.CharField(max_length=80)),
                ('cc_1', models.CharField(max_length=80)),
                ('hasc_1', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            bases=(models.Model, indonesia.interfaces.IndonesiaAdministrativeArea, indonesia.interfaces.AreaPropertyInfo),
        ),
        migrations.AddField(
            model_name='kelurahanborder',
            name='buildings',
            field=models.ManyToManyField(through='indonesia.KelurahanBuilding', to='buildings.Buildings'),
        ),
    ]
