# Generated by Django 2.1.1 on 2018-10-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indonesia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelurahanbuilding',
            name='building',
        ),
        migrations.RemoveField(
            model_name='kelurahanbuilding',
            name='kelurahan',
        ),
        migrations.RemoveField(
            model_name='kelurahanborder',
            name='buildings',
        ),
        migrations.DeleteModel(
            name='KelurahanBuilding',
        ),
    ]
